# Generated by Django 6.0 on 2025-12-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('nacionalidade', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(choices=[('FIC', 'Ficção'), ('NAO', 'Não-Ficção'), ('ROM', 'Romance'), ('FAN', 'Fantasia'), ('POL', 'Policial'), ('BIO', 'Biografia'), ('TEC', 'Técnico'), ('OUT', 'Outros')], max_length=3, verbose_name='Gênero')),
                ('ano_publicacao', models.IntegerField(verbose_name='Ano de Publicação')),
                ('numero_paginas', models.IntegerField(verbose_name='Número de Páginas')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
                ('sinopse', models.TextField(blank=True, null=True, verbose_name='Sinopse')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='biblioteca.autor', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
